# TPDA - QRT
# Configurations
# All source paths are relative to CWD
# All destination paths are relative to 'cfg_p'
---
configs:
  misc:
    # Query definition files extension
    cfg_qdf_ext: qdf
    # User configuration path
    cfg_p: .tpda-qrt
    src_p: share
  general:
    src: config/general.yml
    dst: etc/general.yml
    var: cfg_gen_qn
  toolbar:
    src: config/interfaces/toolbar.yml
    dst: etc/interfaces/toolbar.yml
    var: cfg_tlb_qn
  template:
    src: template/template.qdf
    dst: etc/template/template.qdf
    var: cfg_qdft_qn
  database:
    src: template/connection.yml
    dst: etc/template/connection.yml
    var: cfg_dbt_p
icons:
  path:
    src: config/interfaces/icons
    dst: etc/interfaces/icons
    var: cfg_ico_p
