# Fisier configurare pentru Pdqm
---
conninfo:
  DBMS:     PostgreSQL
  Server:   localhost
  Database: apollo
  Port:     5432
  User:     stefan
  Pass:     tba790k
rex:
  rdfext:   xml
  rdfpath:  rdef
  rdftempl: template.xml
  fileoutpath: reports
toolbar:
  tb_cn:
    id:      1001
    type:    item_check
    icon:    connectyes16
    action:  toggle connect
    tooltip: Connect/disconnect
    help:    Connect/disconnect from the database
    sep:     after
  tb_sv:
    id:      1002
    type:    item_normal
    icon:    filesave16
    action:  report_save
    tooltip: Save
    help:    Save query definition file
    sep:     none
  tb_rf:
    id:      1003
    type:    item_normal
    icon:    actreload16
    action:  report_data_refresh
    tooltip: Refresh
    help:    Refresh data
    sep:     after
  tb_ad:
    id:      1004
    type:    item_normal
    icon:    actitemadd16
    action:  report_add
    tooltip: Add report
    help:    Create new query definition file
    sep:     none
  tb_rm:
    id:      1005
    type:    item_normal
    icon:    actitemdelete16
    action:  report_remove
    tooltip: Remove
    help:    Remove query definition file
    sep:     none
  tb_ed:
    id:      1006
    type:    item_check
    icon:    edit16
    action:  report_edit
    tooltip: Edit
    help:    Edit mode on/off
    sep:     after
  tb_ls:
    id:      1007
    type:    item_list
    action:  choice_change
    sep:     after
  tb_go:
    id:      1008
    type:    item_normal
    icon:    navforward16
    action:  report_run
    tooltip: Run
    help:    Run export
    sep:     after
  tb_qt:
    id:      1009
    type:    item_normal
    icon:    actexit16
    action:  button_exit
    tooltip: Quit
    help:    Quit the application
    sep:     none
